# Generated by Django 5.0.2 on 2024-03-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin"), ("seller", "Seller")],
                default="user",
                max_length=20,
            ),
        ),
    ]
