# Generated by Django 5.0.2 on 2024-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('seller', 'Seller')], default='client', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
