# Generated by Django 5.0.2 on 2024-05-19 23:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='/static/avatar.png', null=True, upload_to=accounts.models.user_image_name),
        ),
    ]
