# Generated by Django 5.0.2 on 2024-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('resolved', 'resolved'), ('closed', 'closed')], default='pending', max_length=10),
        ),
    ]
