# Generated by Django 5.0.2 on 2024-05-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0002_alter_complain_status'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='product',
        ),
        migrations.AddField(
            model_name='complain',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complains', to='orders.order'),
            preserve_default=False,
        ),
    ]
