version: "3.8"

services:
  backend:
    container_name: stocksync_backend
    mem_limit: 500m
    cpus: 0.5
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/backend/static/:/backend/static/
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
  admin-web:
    build:
      context: ./admin
    # ports:
    #   - "4173:4173"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./volumes/admin-web:/admin/dist/
    restart: unless-stopped

    # mem_limit: 500m
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/admin-web:/var/www/admin-web
      - ./volumes/backend/static:/var/www/staticfiles

    depends_on:
      - backend
      - admin-web
  db:
    container_name: stocnsync_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    mem_limit: 500m # Limit memory to 500 MB
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: unless-stopped
