version: '3.8'

services:
  backend:
    container_name: stocksync_backend
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./volumes/backend/static/:/backend/static/
    environment:
      SECRET_KEY: '2039upjfk09u21pokfhipo1ljdwa'
      # DEBUG: 'TRUE'
      HOST: 'localhost'
      DB_NAME: 'stocksync'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_HOST: db
      DB_PORT: '3306'
      WEB_CLIENT_HOST: 'http://localhost'
    mem_limit: 500m
    restart: unless-stopped
    depends_on:
      - db
  admin-web:
    build:
      context: ./admin
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      VITE_SERVER_HOST: 'http://localhost:8000'
    volumes:
      - ./volumes/admin-web:/admin/dist/
    restart: unless-stopped
    # mem_limit: 500m
  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
    volumes:
      - ./volumes/nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/admin-web:/var/www/admin-web
      - ./volumes/backend/static:/var/www/staticfiles

    depends_on:
      - backend
      - admin-web
  db:
    container_name: stocnsync_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'stocksync'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    mem_limit: 500m # Limit memory to 500 MB
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: unless-stopped
