# Generated by Django 5.0.2 on 2024-05-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_items_orderitems_order'),
        ('products', '0005_product_favored_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
