# Generated by Django 5.0.2 on 2024-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='phone',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
