# Generated by Django 5.0.2 on 2024-05-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('received', 'Received'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
