
services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "4000:8000"
    container_name: stocnsync_django
    environment:
      SECRET_KEY: '032hgwpqkfmn3tj20pf2htijwfe'
      DB_NAME: 'stocksync'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_HOST: db
      DB_PORT: '3306'
      WEB_CLIENT_HOST: 'http://localhost:5173'
    # volumes:
    #   - ./:/app
    restart: unless-stopped
    mem_limit: 500m  # Limit memory to 500 MB
    depends_on:
      - db 
      # - redis 
  
  db:
    container_name: stocksync_mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'stocksync'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    mem_limit: 500m  # Limit memory to 500 MB
    volumes:
      - ./docker_volumes/db:/var/lib/mysql
    restart: unless-stopped
  # redis:
  #   container_name: stocnsync_redis
  #   image: redis:7.2-alpine
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 20 1 --loglevel warning --requirepass pass
  #   volumes:
  #     - ./docker_volumes/redis:/data

