# Generated by Django 5.0.2 on 2024-05-23 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_user_productcategory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcoupon',
            name='seller',
        ),
        migrations.AddField(
            model_name='productcoupon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generated_coupons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
